export const records = [
  {
    id: 1,
    check: false,
    status: '분석 완료됨',
    title: 'AI 기반 프로젝트',
    date: '2025-01-14',
    tag: '강연',
    content: 'AI 기반 프로젝트의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 2,
    check: false,
    status: '분석 진행 중',
    title: '스마트 시티 개발',
    date: '2024-11-03',
    tag: '발표',
    content: '스마트 시티 개발의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 3,
    check: false,
    status: '분석 실패',
    title: '데이터 분석 시스템',
    date: '2025-05-27',
    tag: '연설',
    content: '데이터 분석 시스템의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 4,
    check: false,
    status: '분석 완료됨',
    title: '블록체인 솔루션',
    date: '2024-08-19',
    tag: '기타',
    content: '블록체인 솔루션의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 5,
    check: false,
    status: '분석 진행 중',
    title: '웹 서비스 자동화',
    date: '2024-07-16',
    tag: '강연',
    content: '웹 서비스 자동화의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 6,
    check: false,
    status: '분석 실패',
    title: '클라우드 최적화',
    date: '2024-04-05',
    tag: '발표',
    content: '클라우드 최적화의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 7,
    check: false,
    status: '분석 완료됨',
    title: '보안 정책 개선',
    date: '2025-09-21',
    tag: '기타',
    content: '보안 정책 개선의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 8,
    check: false,
    status: '분석 진행 중',
    title: '모바일 UX 향상',
    date: '2025-03-08',
    tag: '강연',
    content: '모바일 UX 향상의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 9,
    check: false,
    status: '분석 실패',
    title: '프로젝트 Z',
    date: '2025-10-11',
    tag: '발표',
    content: '프로젝트 Z의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 10,
    check: false,
    status: '분석 완료됨',
    title: 'AI 음성 인식 엔진',
    date: '2025-06-10',
    tag: '연설',
    content: 'AI 음성 인식 엔진의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 11,
    check: false,
    status: '분석 실패',
    title: '자율주행 기술',
    date: '2024-10-20',
    tag: '강연',
    content: '자율주행 기술의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 12,
    check: false,
    status: '분석 완료됨',
    title: '스마트 로봇 시스템',
    date: '2024-12-02',
    tag: '발표',
    content: '스마트 로봇 시스템의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 13,
    check: false,
    status: '분석 진행 중',
    title: '프로젝트 A1',
    date: '2025-04-22',
    tag: '기타',
    content: '프로젝트 A1의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 14,
    check: false,
    status: '분석 실패',
    title: '빅데이터 예측 모델',
    date: '2024-09-09',
    tag: '강연',
    content: '빅데이터 예측 모델의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 15,
    check: false,
    status: '분석 완료됨',
    title: '재난 대응 시스템',
    date: '2025-08-15',
    tag: '발표',
    content: '재난 대응 시스템의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 16,
    check: false,
    status: '분석 진행 중',
    title: '스마트 팩토리',
    date: '2025-03-19',
    tag: '연설',
    content: '스마트 팩토리의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 17,
    check: false,
    status: '분석 실패',
    title: '딥러닝 엔진',
    date: '2024-02-17',
    tag: '기타',
    content: '딥러닝 엔진의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 18,
    check: false,
    status: '분석 완료됨',
    title: '프로젝트 B2',
    date: '2024-05-06',
    tag: '발표',
    content: '프로젝트 B2의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 19,
    check: false,
    status: '분석 진행 중',
    title: 'AI 최적화 서버',
    date: '2024-03-22',
    tag: '연설',
    content: 'AI 최적화 서버의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 20,
    check: false,
    status: '분석 실패',
    title: '에너지 절감 시스템',
    date: '2025-11-27',
    tag: '강연',
    content: '에너지 절감 시스템의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 21,
    check: false,
    status: '분석 완료됨',
    title: '데이터 암호화 모듈',
    date: '2024-01-25',
    tag: '발표',
    content: '데이터 암호화 모듈의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 22,
    check: false,
    status: '분석 진행 중',
    title: '스마트 건축 설비',
    date: '2025-02-14',
    tag: '기타',
    content: '스마트 건축 설비의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 23,
    check: false,
    status: '분석 실패',
    title: '프로젝트 X12',
    date: '2024-06-18',
    tag: '연설',
    content: '프로젝트 X12의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 24,
    check: false,
    status: '분석 완료됨',
    title: 'Edge 컴퓨팅',
    date: '2024-08-13',
    tag: '발표',
    content: 'Edge 컴퓨팅의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 25,
    check: false,
    status: '분석 진행 중',
    title: 'AI 테스트 자동화',
    date: '2025-01-31',
    tag: '강연',
    content: 'AI 테스트 자동화의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 26,
    check: false,
    status: '분석 실패',
    title: '재무 분석 챗봇',
    date: '2025-10-08',
    tag: '기타',
    content: '재무 분석 챗봇의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 27,
    check: false,
    status: '분석 완료됨',
    title: 'IoT 디바이스 연결',
    date: '2025-03-09',
    tag: '강연',
    content: 'IoT 디바이스 연결의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 28,
    check: false,
    status: '분석 진행 중',
    title: '영상 인식 시스템',
    date: '2024-02-11',
    tag: '발표',
    content: '영상 인식 시스템의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 29,
    check: false,
    status: '분석 실패',
    title: '프로젝트 M9',
    date: '2025-05-29',
    tag: '연설',
    content: '프로젝트 M9의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 30,
    check: false,
    status: '분석 완료됨',
    title: '스마트 에너지 조정',
    date: '2024-07-05',
    tag: '기타',
    content: '스마트 에너지 조정의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 31,
    check: false,
    status: '분석 진행 중',
    title: 'AI 튜닝 플랫폼',
    date: '2024-04-11',
    tag: '발표',
    content: 'AI 튜닝 플랫폼의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 32,
    check: false,
    status: '분석 실패',
    title: '예측 시스템 T3',
    date: '2024-06-17',
    tag: '강연',
    content: '예측 시스템 T3의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 33,
    check: false,
    status: '분석 완료됨',
    title: '보안 모듈 Z1',
    date: '2024-11-22',
    tag: '연설',
    content: '보안 모듈 Z1의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 34,
    check: false,
    status: '분석 진행 중',
    title: 'AI 자동 회의록',
    date: '2024-03-28',
    tag: '강연',
    content: 'AI 자동 회의록의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 35,
    check: false,
    status: '분석 실패',
    title: '프로젝트 Vision',
    date: '2025-09-15',
    tag: '기타',
    content: '프로젝트 Vision의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 36,
    check: false,
    status: '분석 완료됨',
    title: '도시 데이터 허브',
    date: '2024-05-19',
    tag: '발표',
    content: '도시 데이터 허브의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 37,
    check: false,
    status: '분석 진행 중',
    title: 'AI 추천 엔진',
    date: '2025-02-02',
    tag: '연설',
    content: 'AI 추천 엔진의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 38,
    check: false,
    status: '분석 실패',
    title: '딥러닝 서버',
    date: '2024-01-03',
    tag: '기타',
    content: '딥러닝 서버의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 39,
    check: false,
    status: '분석 완료됨',
    title: '스마트 보안 게이트',
    date: '2025-07-26',
    tag: '발표',
    content: '스마트 보안 게이트의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 40,
    check: false,
    status: '분석 진행 중',
    title: '클라우드 자동 확장',
    date: '2024-12-21',
    tag: '연설',
    content: '클라우드 자동 확장의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 41,
    check: false,
    status: '분석 실패',
    title: '프로젝트 Y10',
    date: '2024-11-08',
    tag: '강연',
    content: '프로젝트 Y10의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 42,
    check: false,
    status: '분석 완료됨',
    title: 'AI 음성 분석',
    date: '2025-05-12',
    tag: '발표',
    content: 'AI 음성 분석의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 43,
    check: false,
    status: '분석 진행 중',
    title: '스마트 교통 시스템',
    date: '2024-02-26',
    tag: '기타',
    content: '스마트 교통 시스템의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 44,
    check: false,
    status: '분석 실패',
    title: '보안 데이터 연동',
    date: '2024-09-04',
    tag: '연설',
    content: '보안 데이터 연동의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 45,
    check: false,
    status: '분석 완료됨',
    title: '클라우드 메시지 브로커',
    date: '2025-04-13',
    tag: '발표',
    content: '클라우드 메시지 브로커의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 46,
    check: false,
    status: '분석 진행 중',
    title: 'AI 제품 추천',
    date: '2024-10-29',
    tag: '기타',
    content: 'AI 제품 추천의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 47,
    check: false,
    status: '분석 실패',
    title: '스마트 냉난방',
    date: '2024-05-21',
    tag: '강연',
    content: '스마트 냉난방의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 48,
    check: false,
    status: '분석 완료됨',
    title: '프로젝트 K5',
    date: '2025-06-01',
    tag: '연설',
    content: '프로젝트 K5의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 49,
    check: false,
    status: '분석 진행 중',
    title: '기계 학습 파이프라인',
    date: '2024-03-05',
    tag: '발표',
    content: '기계 학습 파이프라인의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 50,
    check: false,
    status: '분석 실패',
    title: 'AI 시각화 도구',
    date: '2025-11-17',
    tag: '기타',
    content: 'AI 시각화 도구의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 51,
    check: false,
    status: '분석 완료됨',
    title: '차세대 서버',
    date: '2024-01-19',
    tag: '발표',
    content: '차세대 서버의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 52,
    check: false,
    status: '분석 진행 중',
    title: '프로젝트 L8',
    date: '2025-10-05',
    tag: '강연',
    content: '프로젝트 L8의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 53,
    check: false,
    status: '분석 실패',
    title: '스마트 교실',
    date: '2025-09-12',
    tag: '연설',
    content: '스마트 교실의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 54,
    check: false,
    status: '분석 완료됨',
    title: '영상 분류 엔진',
    date: '2024-08-23',
    tag: '기타',
    content: '영상 분류 엔진의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 55,
    check: false,
    status: '분석 진행 중',
    title: '경로 탐색 시스템',
    date: '2025-06-18',
    tag: '강연',
    content: '경로 탐색 시스템의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 56,
    check: false,
    status: '분석 실패',
    title: '에너지 관제 플랫폼',
    date: '2024-07-25',
    tag: '발표',
    content: '에너지 관제 플랫폼의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 57,
    check: false,
    status: '분석 완료됨',
    title: '감정 분석 AI',
    date: '2025-03-25',
    tag: '연설',
    content: '감정 분석 AI의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 58,
    check: false,
    status: '분석 진행 중',
    title: '프로젝트 Omega',
    date: '2024-04-09',
    tag: '기타',
    content: '프로젝트 Omega의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 59,
    check: false,
    status: '분석 실패',
    title: 'AI 자동 점검',
    date: '2025-05-01',
    tag: '발표',
    content: 'AI 자동 점검의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 60,
    check: false,
    status: '분석 완료됨',
    title: '스마트 주차 시스템',
    date: '2024-11-13',
    tag: '강연',
    content: '스마트 주차 시스템의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 61,
    check: false,
    status: '분석 진행 중',
    title: '프로젝트 Z3',
    date: '2024-06-14',
    tag: '연설',
    content: '프로젝트 Z3의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 62,
    check: false,
    status: '분석 실패',
    title: 'AI 얼굴 인식 보안',
    date: '2025-08-02',
    tag: '발표',
    content: 'AI 얼굴 인식 보안의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 63,
    check: false,
    status: '분석 완료됨',
    title: '스마트 농업 제어',
    date: '2025-01-08',
    tag: '강연',
    content: '스마트 농업 제어의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 64,
    check: false,
    status: '분석 진행 중',
    title: '프로젝트 Q7',
    date: '2024-02-28',
    tag: '기타',
    content: '프로젝트 Q7의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 65,
    check: false,
    status: '분석 실패',
    title: '예측 유지보수',
    date: '2024-10-24',
    tag: '발표',
    content: '예측 유지보수의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 66,
    check: false,
    status: '분석 완료됨',
    title: 'AI 비서 시스템',
    date: '2025-09-04',
    tag: '강연',
    content: 'AI 비서 시스템의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 67,
    check: false,
    status: '분석 진행 중',
    title: '딥러닝 가속기',
    date: '2025-12-14',
    tag: '연설',
    content: '딥러닝 가속기의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 68,
    check: false,
    status: '분석 실패',
    title: '스마트 헬스케어',
    date: '2024-05-02',
    tag: '기타',
    content: '스마트 헬스케어의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 69,
    check: false,
    status: '분석 완료됨',
    title: 'AI 서비스 모니터링',
    date: '2025-04-07',
    tag: '발표',
    content: 'AI 서비스 모니터링의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 70,
    check: false,
    status: '분석 진행 중',
    title: '도시 교통 관리',
    date: '2024-09-17',
    tag: '연설',
    content: '도시 교통 관리의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 71,
    check: false,
    status: '분석 실패',
    title: '스마트 센서 네트워크',
    date: '2025-02-10',
    tag: '강연',
    content: '스마트 센서 네트워크의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 72,
    check: false,
    status: '분석 완료됨',
    title: 'AI 자동 채점 시스템',
    date: '2024-01-29',
    tag: '발표',
    content: 'AI 자동 채점 시스템의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 73,
    check: false,
    status: '분석 진행 중',
    title: '프로젝트 Delta',
    date: '2025-05-19',
    tag: '기타',
    content: '프로젝트 Delta의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 74,
    check: false,
    status: '분석 실패',
    title: '영상 인식 도구',
    date: '2024-07-02',
    tag: '연설',
    content: '영상 인식 도구의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 75,
    check: false,
    status: '분석 완료됨',
    title: 'AI 기반 진단',
    date: '2025-08-12',
    tag: '발표',
    content: 'AI 기반 진단의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 76,
    check: false,
    status: '분석 진행 중',
    title: '스마트 전력 관리',
    date: '2025-11-09',
    tag: '강연',
    content: '스마트 전력 관리의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 77,
    check: false,
    status: '분석 실패',
    title: '프로젝트 Nano',
    date: '2024-06-22',
    tag: '기타',
    content: '프로젝트 Nano의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 78,
    check: false,
    status: '분석 완료됨',
    title: 'AI 금융 분석',
    date: '2024-03-12',
    tag: '발표',
    content: 'AI 금융 분석의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 79,
    check: false,
    status: '분석 진행 중',
    title: '프로젝트 Beam',
    date: '2024-10-07',
    tag: '연설',
    content: '프로젝트 Beam의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 80,
    check: false,
    status: '분석 실패',
    title: '보안 침입 탐지',
    date: '2025-12-03',
    tag: '강연',
    content: '보안 침입 탐지의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 81,
    check: false,
    status: '분석 완료됨',
    title: '스마트 도로',
    date: '2024-08-01',
    tag: '기타',
    content: '스마트 도로의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 82,
    check: false,
    status: '분석 진행 중',
    title: 'AI 이미지 생성',
    date: '2025-09-01',
    tag: '발표',
    content: 'AI 이미지 생성의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 83,
    check: false,
    status: '분석 실패',
    title: '프로젝트 CloudX',
    date: '2024-04-25',
    tag: '강연',
    content: '프로젝트 CloudX의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 84,
    check: false,
    status: '분석 완료됨',
    title: 'AI 품질 검증',
    date: '2025-01-05',
    tag: '연설',
    content: 'AI 품질 검증의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 85,
    check: false,
    status: '분석 진행 중',
    title: '스마트 출입 관리',
    date: '2024-02-06',
    tag: '발표',
    content: '스마트 출입 관리의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 86,
    check: false,
    status: '분석 실패',
    title: '프로젝트 Metro',
    date: '2025-07-30',
    tag: '기타',
    content: '프로젝트 Metro의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 87,
    check: false,
    status: '분석 완료됨',
    title: 'AI 감시 시스템',
    date: '2024-05-09',
    tag: '연설',
    content: 'AI 감시 시스템의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 88,
    check: false,
    status: '분석 진행 중',
    title: '스마트 주거 플랫폼',
    date: '2025-06-21',
    tag: '강연',
    content: '스마트 주거 플랫폼의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 89,
    check: false,
    status: '분석 실패',
    title: '프로젝트 Titan',
    date: '2025-10-23',
    tag: '발표',
    content: '프로젝트 Titan의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 90,
    check: false,
    status: '분석 완료됨',
    title: 'AI 프로젝트 관리',
    date: '2025-09-19',
    tag: '발표',
    content: 'AI 프로젝트 관리의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 91,
    check: false,
    status: '분석 진행 중',
    title: '스마트 교통 모니터링',
    date: '2024-03-17',
    tag: '기타',
    content: '스마트 교통 모니터링의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 92,
    check: false,
    status: '분석 실패',
    title: 'AI 자동 레포팅',
    date: '2024-11-29',
    tag: '연설',
    content: 'AI 자동 레포팅의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 93,
    check: false,
    status: '분석 완료됨',
    title: '프로젝트 Hyper',
    date: '2025-02-03',
    tag: '강연',
    content: '프로젝트 Hyper의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 94,
    check: false,
    status: '분석 진행 중',
    title: '스마트 자산 관리',
    date: '2024-06-30',
    tag: '발표',
    content: '스마트 자산 관리의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 95,
    check: false,
    status: '분석 실패',
    title: '예측형 분석 엔진',
    date: '2025-12-28',
    tag: '기타',
    content: '예측형 분석 엔진의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 96,
    check: false,
    status: '분석 완료됨',
    title: 'IoT 기반 방재',
    date: '2024-07-08',
    tag: '강연',
    content: 'IoT 기반 방재의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 97,
    check: false,
    status: '분석 진행 중',
    title: '프로젝트 Zero',
    date: '2024-10-14',
    tag: '발표',
    content: '프로젝트 Zero의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 98,
    check: false,
    status: '분석 실패',
    title: 'AI 회의 자동 기록',
    date: '2025-04-30',
    tag: '연설',
    content: 'AI 회의 자동 기록의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 99,
    check: false,
    status: '분석 완료됨',
    title: '스마트 병원 시스템',
    date: '2024-11-11',
    tag: '기타',
    content: '스마트 병원 시스템의 진행 상황과 향후 계획을 공유합니다.',
  },
  {
    id: 100,
    check: false,
    status: '분석 진행 중',
    title: '프로젝트 Nova',
    date: '2025-08-28',
    tag: '발표',
    content: '프로젝트 Nova의 진행 상황과 향후 계획을 공유합니다.',
  },
];
